[phases.setup]
nixPkgs = ["python3", "gcc", "xorg.libX11", "xorg.libxcb", "libglvnd", "glib"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[variables]
LD_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu:/opt/venv/lib/python3.12/site-packages/cv2/qt/plugins:/nix/store"
PYTHONUNBUFFERED = "1"