[phases.setup]
nixPkgs = ["python3", "gcc", "xorg.libX11", "xorg.libxcb", "libglvnd", "glib"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]