[phases.setup]
nixPkgs = ["python3", "gcc", "xorg.libX11", "xorg.libxcb", "libglvnd", "glib"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

# VOEG DIT STUKJE TOE:
[phases.build]
cmds = ["echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/nix/store' >> /opt/venv/bin/activate"]